### ISSUE TITLE
Ошибка при тестовом получении выписки

### ISSUE THREAD

**Issue by viga1979** [Host-to-Host-Instructions/alfalink-1c-directbank-documentation#1]
При попытке получения выписки на тестовой организации получаем вот такой результат:
![image](https://user-images.githubusercontent.com/11483282/166110446-6e4ef943-8113-4eb2-9779-8ab68bf60084.png)

Реквизиты счета копировались, проверка подключения проходит. Но запрос выписки - облом. Не подскажите, что делать?

**Comment by artik008** [comment]
Пришлите, пожалуйста, скриншот страницы настроек обмена с банком. Вы загружали файл настроек из репозитория?

**Comment by viga1979** [comment]
Во вложении файл настроек. Взят из архива (
https://github.com/Host-to-Host-Instructions/alfalink-1c-directbank-via-1c/archive/refs/heads/master.zip).
Так же я пробовал обновлять его из банка.
![image](https://user-images.githubusercontent.com/11483282/166673016-e175c4d9-3cc7-4736-a7da-50d3fd3de7c1.png)
![image](https://user-images.githubusercontent.com/11483282/166673061-e8d05437-ce62-43a7-a3ed-ad67f147e092.png)

**Comment by viga1979** [comment]
Хм. не вижу вложенного файла настроек. Дублирую его.

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Settings xmlns="http://directbank.1c.ru/XMLSchema" id="d0e35843-7907-4bfe-ac7a-61a324577c82" formatVersion="2.2.2" creationDate="2022-01-13T10:22:36.924Z">
	<Sender bic="044525593" name="АО &quot;АЛЬФА-БАНК&quot;"/>
	<Recipient id="40702810701300009144" name="Общество с ограниченной ответственностью &quot;Тест Директ Банк&quot;" inn="0329156629" kpp="043360081"/>
	<Data>
		<CustomerID>40702810701300009144</CustomerID>
		<BankServerAddress>https://grampus-int.alfabank.ru/API/v1/directbank</BankServerAddress>
		<FormatVersion>2.2.2</FormatVersion>
		<Encoding>UTF-8</Encoding>
		<Compress>false</Compress>
		<Logon>
			<Login>
				<User>directBank</User>
			</Login>
		</Logon>
		<CryptoParameters>
			<CSPName>Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider</CSPName>
			<CSPType>80</CSPType>
			<SignAlgorithm>GR 34.10-2012 256</SignAlgorithm>
			<HashAlgorithm>GR 34.11-2012 256</HashAlgorithm>
			<Encrypted>
				<EncryptAlgorithm>GOST 28147-89</EncryptAlgorithm>
			</Encrypted>
			<CustomerSignature>
				<GroupSignatures numberGroup="1">
					<Certificate>MIIDFzCCAsagAwIBAgITEgBeg00bplP6nvyOxgABAF6DTTAIBgYqhQMCAgMwfzEjMCEGCSqGSIb3DQEJARYUc3VwcG9ydEBjcnlwdG9wcm8ucnUxCzAJBgNVBAYTAlJVMQ8wDQYDVQQHEwZNb3Njb3cxFzAVBgNVBAoTDkNSWVBUTy1QUk8gTExDMSEwHwYDVQQDExhDUllQVE8tUFJPIFRlc3QgQ2VudGVyIDIwHhcNMjIwNDA4MTQ0NzA0WhcNMjIwNzA4MTQ1NzA0WjAdMRswGQYDVQQDDBJkaXJlY3RCYW5rMjAyMjAyXzEwZjAfBggqhQMHAQEBATATBgcqhQMCAiQABggqhQMHAQECAgNDAARAIihFgzMUhqZFBqjpsUSr8Cf/BnqrQZp3GhFB/1FjqEu4ExB04Mt7/ZALOfGGCS+jQP40vVAeMEYH8rVESUhwzKOCAXYwggFyMA4GA1UdDwEB/wQEAwIE8DATBgNVHSUEDDAKBggrBgEFBQcDAjAdBgNVHQ4EFgQU4MI7sx5QjV4XAjmziJNXg6puKJ0wHwYDVR0jBBgwFoAUToM+FGnv7F16lStfEf43MhZJVSswXAYDVR0fBFUwUzBRoE+gTYZLaHR0cDovL3Rlc3RjYS5jcnlwdG9wcm8ucnUvQ2VydEVucm9sbC9DUllQVE8tUFJPJTIwVGVzdCUyMENlbnRlciUyMDIoMSkuY3JsMIGsBggrBgEFBQcBAQSBnzCBnDBkBggrBgEFBQcwAoZYaHR0cDovL3Rlc3RjYS5jcnlwdG9wcm8ucnUvQ2VydEVucm9sbC90ZXN0LWNhLTIwMTRfQ1JZUFRPLVBSTyUyMFRlc3QlMjBDZW50ZXIlMjAyKDEpLmNydDA0BggrBgEFBQcwAYYoaHR0cDovL3Rlc3RjYS5jcnlwdG9wcm8ucnUvb2NzcC9vY3NwLnNyZjAIBgYqhQMCAgMDQQDbjqMj0MG9fB5fI7aZggBThK94qFs8cecfUHb36T0z8WOKbitjsvpuFKdHjAfNKwQH2PrlMAhrIDW8fQI7WN4z</Certificate>
				</GroupSignatures>
			</CustomerSignature>
		</CryptoParameters>
		<Document docKind="01"/>
		<Document docKind="02"/>
		<Document docKind="03"/>
		<Document docKind="05"/>
		<Document docKind="06"/>
		<Document docKind="10">
			<Signed>
				<RuleSignatures>(1)</RuleSignatures>
			</Signed>
		</Document>
		<Document docKind="14"/>
		<Document docKind="15"/>
		<Document docKind="19"/>
		<Document docKind="20"/>
		<Document docKind="21"/>
		<Document docKind="22"/>
	</Data>
</Settings>

**Comment by artik008** [comment]
Ошибка возникла из-за того, что документ был направлен с неверным счётом в хедерах. В логах права проверяются по счёту *6411. Такого нет в тестовой системе. Должна быть отправка от 40702810701300009144. Проверьте, правильно ли у вас при отправке выбрана организация и счёт.

**Comment by viga1979** [comment]
Все верно. Неверно был почему то заполнен номер счета. Очень странно. Приношу извинения. Тестовое получение выписки завершено успешно. Спасибо.
